#!/bin/bash
# Manual Release Creation Script for NextMap
# Use when GitHub Actions workflow has issues

echo "🚀 NextMap Manual Release Creator"
echo "================================="

VERSION="v0.2.3"
REPO="pozivo/nextmap"

echo "📋 This script helps create manual releases when automation fails"
echo "Version: $VERSION"
echo "Repository: $REPO"
echo ""

echo "📁 Local Build Instructions:"
echo "1. Build all platforms:"
echo "   cargo build --release --target x86_64-pc-windows-msvc"
echo "   cargo build --release --target x86_64-unknown-linux-gnu"
echo "   cargo build --release --target x86_64-unknown-linux-musl"
echo "   cargo build --release --target x86_64-apple-darwin"
echo "   cargo build --release --target aarch64-apple-darwin"
echo ""

echo "📦 Archive Creation:"
echo "2. Create archives:"
echo "   # Windows"
echo "   mkdir release-windows && cp target/x86_64-pc-windows-msvc/release/nextmap.exe release-windows/"
echo "   cd release-windows && zip ../nextmap-windows-x64.zip * && cd .."
echo ""
echo "   # Linux"
echo "   mkdir release-linux && cp target/x86_64-unknown-linux-gnu/release/nextmap release-linux/"
echo "   cd release-linux && tar -czf ../nextmap-linux-x64.tar.gz * && cd .."
echo ""
echo "   # Linux MUSL"
echo "   mkdir release-musl && cp target/x86_64-unknown-linux-musl/release/nextmap release-musl/"
echo "   cd release-musl && tar -czf ../nextmap-linux-musl-x64.tar.gz * && cd .."
echo ""
echo "   # macOS Intel"
echo "   mkdir release-macos && cp target/x86_64-apple-darwin/release/nextmap release-macos/"
echo "   cd release-macos && tar -czf ../nextmap-macos-x64.tar.gz * && cd .."
echo ""
echo "   # macOS ARM"
echo "   mkdir release-arm && cp target/aarch64-apple-darwin/release/nextmap release-arm/"
echo "   cd release-arm && tar -czf ../nextmap-macos-arm64.tar.gz * && cd .."
echo ""

echo "🌐 GitHub Release Creation:"
echo "3. Create release on GitHub:"
echo "   - Go to: https://github.com/$REPO/releases/new"
echo "   - Tag: $VERSION"
echo "   - Title: NextMap $VERSION"
echo "   - Upload the 5 archives created above"
echo ""

echo "💡 Alternative - GitHub CLI:"
echo "4. If you have GitHub CLI installed:"
echo "   gh release create $VERSION *.zip *.tar.gz \\"
echo "     --title \"NextMap $VERSION\" \\"
echo "     --notes \"See CHANGELOG.md for details\""
echo ""

echo "🔧 Troubleshooting GitHub Actions:"
echo "- Check: https://github.com/$REPO/actions"
echo "- Look for failed workflows and error logs"
echo "- Common issues: permissions, file patterns, dependencies"
echo ""

echo "✅ Manual release creation ready!"
echo "Follow the steps above if automated workflow fails."